# Generated by Django 5.1 on 2024-09-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id_benefactor', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id_datos_bancarios', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=50)),
                ('nombre_dueno', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('no_ext', models.IntegerField()),
                ('no_int', models.IntegerField()),
                ('colonia', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MCO',
            fields=[
                ('id_mco', models.AutoField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('ppal', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id_persona_fisica', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaMoral',
            fields=[
                ('id_persona_moral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('representante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donativo',
            fields=[
                ('id_donativo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_categoria', models.IntegerField()),
                ('id_subcategoria', models.IntegerField()),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('id_benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.benefactor')),
            ],
        ),
        migrations.CreateModel(
            name='DonativoEntregado',
            fields=[
                ('id_donativo_entregado', models.AutoField(primary_key=True, serialize=False)),
                ('id_beneficiario', models.IntegerField()),
                ('id_donativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.donativo')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarioPersonaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.beneficiario')),
                ('id_persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personafisica')),
            ],
        ),
        migrations.CreateModel(
            name='BenefactorPersonaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.benefactor')),
                ('id_persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personafisica')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFisicaDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.direccion')),
                ('id_persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personafisica')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFisicaMCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.mco')),
                ('id_persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personafisica')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarioPersonaMoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.beneficiario')),
                ('id_persona_moral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personamoral')),
            ],
        ),
        migrations.CreateModel(
            name='BenefactorPersonaMoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.benefactor')),
                ('id_persona_moral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personamoral')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaMoralDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.direccion')),
                ('id_persona_moral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personamoral')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaMoralMCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.mco')),
                ('id_persona_moral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personamoral')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_voluntario', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionSeminario.personafisica')),
            ],
        ),
    ]
